
services: 

  ib-nginx:
    image: nginx
    container_name: ib-nginx
    depends_on: 
      - ib-api
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./certificate.key:/etc/nginx/ssl/certificate.key
  ib-api:
    image: mkayyee/ib-api
    container_name: ib-api
    ports:
      - 8081:8081
    restart: always

    
